<a href="https://colab.research.google.com/github/Parth1132/Face-Mask-Detection-CNN/blob/main/Neural__Network_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

def sigmoid(x):
  return 1/(1*np.exp(-x))

def sigmoid_derivative(x):
  return x * (1-x)

training_inputs = np.array([[0,1,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1],
                            ])
training_output = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) - 1

print('Random starting synatptic weights:')
print(synaptic_weights)

for iteration in range(1000):

  input_layer = training_inputs

  outputs = sigmoid(np.dot(input_layer, synaptic_weights))

  error = training_output - outputs

  adjustments = error * sigmoid_derivative(outputs)

  synaptic_weights = np.dot(input_layer.T, adjustments)

print('Synaptic weights after training')
print(synaptic_weights)

print('Output after training:')
print(outputs)







Random starting synatptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training
[[ 0.11579503]
 [-0.20161256]
 [-0.17264105]]
Output after training:
[[0.60183963]
 [0.62824821]
 [0.81099342]
 [0.60183963]]


**[[]] (Nested Square Brackets):**

1.Represents a list containing one or more sublists.


2.When used to represent a matrix, [[]] denotes a two-dimensional matrix where each sublist represents a row or column of the matrix.


**Example**: matrix = [[]] would represent a matrix with one row (empty row) and zero columns.

**Important**

1.np.dot(input_layer, synaptic_weights) performs matrix multiplication between the input_layer and synaptic_weights, resulting in a weighted sum of the inputs.

2.The sigmoid() function applies the sigmoid activation function element-wise to the result of the dot product.


